import {StyleSheet,StatusBar,Dimensions} from "react-native"


export default  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    mainview:{
      flex:1, 
      // marginTop:StatusBar.currentHeight,
      backgroundColor:"white",
      height:Dimensions.get("window").height - StatusBar.currentHeight,
      width:Dimensions.get("window").width,
      alignItems: 'center',
      justifyContent: 'center',
      // marginHorizontal:17
      padding:10,
      },
      button1:{   
        height:36,
        flex:0.1,
        // backgroundColor:"red",
        // margin:8,
        alignItems:"flex-start",
        // justifyContent:"space-between",
        borderRadius:5,
        // borderWidth:2,
        padding:6,
        // elevation:1,
      },
      text:{
        fontSize:22,
        flex:0.9,
        color:"purple",
        textAlign:"center",
        fontWeight:"bold"
      },
      Images:{
        height:28,
        width:30,
        resizeMode:"contain",
        // marginTop:15,
        // marginRight:2,
       },
      textinput1:{
        height:40,
        width:"48%",
        // margin:8,
        // backgroundColor:"red",
        // paddingHorizontal:2,
      //   padding:10,
        borderWidth:1,
        borderRadius:5,
        borderColor: 'white', 
        color:"black",
        fontWeight:'bold',
        fontSize:14,
        paddingLeft:12,
        fontWeight:"700",
        
        elevation:1,
        shadowOffset: { width: 1, height: 1 },
        shadowColor: 'gray',
        shadowOpacity: 0.3,
        },
        textinput2:{
          height:40,
          width:"100%",
          // margin:8,
          // backgroundColor:"red",
          // paddingHorizontal:2,
        //   padding:10,
          borderWidth:1,
          borderRadius:5,
          borderColor: 'white', 
          color:"black",
          fontWeight:'bold',
          fontSize:14,
          paddingLeft:12,
          fontWeight:"700",
          elevation:1,
          shadowOffset: { width: 1, height: 1 },
          shadowColor: 'gray',
          shadowOpacity: 0.3,
          marginTop:10,
          },
          logbutton:{
            height:50,
            width:"100%",
            backgroundColor:"purple",
            margin:8,
            alignItems:"center",
            // justifyContent:"space-evenly",
            borderRadius:5,
            // borderWidth:2,
            padding:16,
            color:"red",
            alignSelf:"center",
            marginTop:18,
            },
            logbutton1:{   
              alignSelf:"center",
              // elevation:6,
              fontSize:22,
              },
    });