import {StyleSheet,StatusBar,Dimensions} from "react-native"

export default  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    mainview:{
      flex:1, 
      marginTop:StatusBar.currentHeight,
      backgroundColor:"white",
      height:Dimensions.get("window").height - StatusBar.currentHeight,
      width:Dimensions.get("window").width,
      alignItems: 'center',
      // justifyContent: 'center',
      // marginHorizontal:17
      padding:15,
      },
      DBmages:{
        height:170,
        width:290,
        resizeMode:"contain",
       },
       text:{
        marginTop:12,
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        fontWeight:"bold",
       },
       text1:{
        marginTop:1,
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        fontWeight:"bold",
       },
       textinput2:{
        height:40,
        width:"99%",
        marginLeft:0.5,
        marginRight:0.5,
        // backgroundColor:"red",
        // paddingHorizontal:2,
      //   padding:10,
        borderWidth:1,
        borderRadius:5,
        borderColor: 'white', 
        color:"black",
        fontWeight:'bold',
        fontSize:14,
        paddingLeft:12,
        fontWeight:"700",
        elevation:1,
        shadowOffset: { width: 1, height: 1 },
        shadowColor: 'gray',
        shadowOpacity: 0.3,
        marginTop:15,
        },
        logbutton:{
            height:50,
            width:"100%",
            backgroundColor:"purple",
            margin:8,
            alignItems:"center",
            // justifyContent:"space-evenly",
            borderRadius:5,
            // borderWidth:2,
            padding:16,
            color:"red",
            alignSelf:"center",
            marginTop:22,
            },
            logbutton1:{   
              alignSelf:"center",
              // elevation:6,
              fontSize:22,
              },
    });