import {StyleSheet,StatusBar,Dimensions} from "react-native"

export default  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    mainview:{
      flex:1, 
      // marginTop:StatusBar.currentHeight,
      backgroundColor:"white",
      height:Dimensions.get("window").height - StatusBar.currentHeight,
      // width:Dimensions.get("window").width,
      alignItems: 'center',
      // justifyContent: 'center',
      // marginHorizontal:17
      padding:15,
      },
      textinput1:{
        height:40,
        width:"48%",
        // margin:8,
        // backgroundColor:"red",
        // paddingHorizontal:2,
      //   padding:10,
        borderWidth:1,
        borderRadius:5,
        borderColor: 'white', 
        color:"black",
        fontWeight:'bold',
        fontSize:14,
        paddingLeft:12,
        fontWeight:"700",
        
        elevation:1,
        shadowOffset: { width: 1, height: 1 },
        shadowColor: 'gray',
        shadowOpacity: 0.3,
        },
        textinput2:{
          height:40,
          width:"100%",
          // margin:8,
          // backgroundColor:"red",
          // paddingHorizontal:2,
        //   padding:10,
          borderWidth:1,
          borderRadius:5,
          borderColor: 'white', 
          color:"black",
          fontWeight:'bold',
          fontSize:14,
          paddingLeft:12,
          fontWeight:"700",
          elevation:1,
          shadowOffset: { width: 1, height: 1 },
          shadowColor: 'gray',
          shadowOpacity: 0.3,
          marginTop:10,
          },
          logbutton:{
            height:50,
            width:"100%",
            backgroundColor:"purple",
            margin:8,
            alignItems:"center",
            // justifyContent:"space-evenly",
            borderRadius:5,
            // borderWidth:2,
            padding:16,
            color:"red",
            alignSelf:"center",
            marginTop:18,
            },
            logbutton1:{   
              alignSelf:"center",
              // elevation:6,
              fontSize:22,
              },
              picker:{ 
                height: 44, 
                marginTop:10,
                width:"100%",
                // flex:1,
                borderWidth:0,
                borderRadius:1,
                shadowOffset: { width: 1, height: 1 },
                shadowColor: 'gray',
                shadowOpacity: 1,
                // borderColor:"red",
                // backgroundColor:"green",
                // borderBottomColor:"yellow" ,
                // margintop:77,
                // color:"green",
                justifyContent:"center",


                padding: 10,
                backgroundColor: "white",
                borderColor: 'white',
                color: '#2c2c2c'
                }
    
});